name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: Ruff (lint + isort)
        run: ruff check .

      - name: Pytest (with coverage)
        run: pytest -q --maxfail=1 --disable-warnings --cov=.

      - name: Fail on placeholders
        run: |
          if grep -R -n --include="*.py" -e '^[[:space:]]*pass[[:space:]]*$' -e '^[[:space:]]*\.\.[[:space:]]*$' . ; then
            echo "Found placeholder 'pass' or '...' in code. Refuse to merge.";
            exit 1;
          fi
